spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/restaurant?useTimezone=true&serverTimezone=America/Sao_Paulo}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq-config:
  queue: order-queue
  exchange: order-exchange
  routing-key: order-routing-key

jwt:
  secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D& ]{ @Vr?G;2?XhbC:Qa#9#eMLN\ }x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
  expiration: 99999999

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

springdoc:
  show-actuator: true