spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq-config:
  queue: order-queue
  exchange: order-exchange
  routing-key: order-routing-key