global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "restaurant-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "3.83.113.31:8080" ]
        labels:
          application: "restaurant-api"