name: Deploy Restaurant Api
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build Project
        run: mvn clean install
      - name: Login Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t giovannilramos/restaurant-api .
      - name: Publish Image
        run: docker push giovannilramos/restaurant-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image Docker Hub
        run: docker pull giovannilramos/restaurant-api:latest
      - name: Remove Container
        run: docker rm -f restaurant-api
      - name: Run Docker Container restaurant-api
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e RABBITMQ_HOST=${{secrets.RABBITMQ_HOST}} RABBITMQ_USERNAME=${{secrets.RABBITMQ_USERNAME}} RABBITMQ_PASSWORD=${{secrets.RABBITMQ_PASSWORD}} --name restaurant-api giovannilramos/restaurant-api
