name: Test Coverage
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean install

      - name: Generate JaCoCo Badges for Module Application
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg
          coverage-label: coverage
          branches-label: branches

      - name: Log Coverage Percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          push: origin main --force
          message: 'chore: change badges coverage'
          add: '*.svg'